language: node_js
dist: focal
before_install:
  - npm config set registry https://:2020-09-13T16%3A23%3A15.885Z@time-machines-npm.sealsecurity.io/
install:
  - npm install --ignore-scripts
before_script:
  - git submodule update --init
jobs:
  include:
    - node_js: "10"
      script:
        - npm run build
        - npm run test-cov
    - node_js: "12"
      script:
        - npm run build
        - npm run test-spec
    - node_js: "14"
      script:
        - npm run build
        - npm run test-spec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9cab5fe0c9595511cd81
    on_success: change
    on_failure: always
    on_start: never
